import type { FocusSession, Habit, HabitCategory, HabitCheckIn } from "../types/habit";
import { getDailyConsistency, getStreaks } from "./consistency";
import { getDayQuality, type DayQuality } from "./dayQuality";
import { addDays, dateFromKey, toDateKey } from "./date";
export interface MonthlyStats { counts: Record<DayQuality, number>; average: number | null; streaks: { current: number; longest: number }; }
const statisticCategories: HabitCategory[] = ["Study", "Career", "Health", "Personal", "Other"];
export function monthBounds(monthKey: string): { start: string; end: string } { const [year, month] = monthKey.split("-").map(Number); return { start: `${monthKey}-01`, end: toDateKey(new Date(year, month, 0)) }; }
export function getMonthlyStats(monthKey: string, habits: Habit[], checkIns: HabitCheckIn[], focusSessions: readonly FocusSession[] = []): MonthlyStats { const { start, end } = monthBounds(monthKey); const counts: Record<DayQuality, number> = { MISSED: 0, SHOWED_UP: 0, GOOD: 0, STRONG: 0, PERFECT: 0, PLANNED_REST: 0 }; let total = 0; let scored = 0; const lastDate = end < toDateKey(new Date()) ? end : toDateKey(new Date()); for (let date = dateFromKey(start); toDateKey(date) <= lastDate; date = addDays(date, 1)) { const summary = getDailyConsistency(toDateKey(date), habits, checkIns, focusSessions); const quality = getDayQuality(summary.score, summary.isPlannedRest); if (quality) counts[quality] += 1; if (summary.score !== null) { total += summary.score; scored += 1; } } return { counts, average: scored ? Math.round(total / scored) : null, streaks: getStreaks(habits, checkIns, focusSessions) }; }
export function getCategoryConsistency(monthKey: string, habits: Habit[], checkIns: HabitCheckIn[], focusSessions: readonly FocusSession[] = []): { category: HabitCategory; score: number | null }[] { const { start, end } = monthBounds(monthKey); const lastDate = end < toDateKey(new Date()) ? end : toDateKey(new Date()); return statisticCategories.map((category) => { let completed = 0; let total = 0; for (let date = dateFromKey(start); toDateKey(date) <= lastDate; date = addDays(date, 1)) { const summary = getDailyConsistency(toDateKey(date), habits.filter((habit) => habit.category === category), checkIns, focusSessions); if (summary.score !== null) { completed += summary.completed; total += summary.completed + summary.missed; } } return { category, score: total ? Math.round((completed / total) * 100) : null }; }); }
